name: SonarQube Analysis

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step 2: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin
          echo "SonarScanner installed"

      # Step 3: Run SonarScanner
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.sources=frontend,backend \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
