name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # or the default branch of your project
  pull_request:
    branches:
      - main  # or the default branch of your project

jobs:
  sonarcloud:
    runs-on: ubuntu-latest  # or another operating system if you prefer

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can use any version of Node.js that fits your project

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Install SonarScanner
    - name: Install SonarScanner
      run: |
        curl -sSLo /tmp/sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.8.0.2856/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip /tmp/sonar-scanner.zip -d /tmp
        export PATH=$PATH:/tmp/sonar-scanner-4.8.0.2856-linux/bin
        sonar-scanner --version  # Verify the installation

    # Run SonarCloud analysis
    - name: Run SonarCloud analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_key \
          -Dsonar.sources=frontend,backend \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
